### ISSUE TITLE
No support for areas

### ISSUE THREAD

**Issue by bpiec** [chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting#1]
Would it be possible to add support for areas? The following route:

```csharp
routes.MapRoute(
	name: "areaRoute",
	template: "api/{area}/{controller}/{id?}"
);
```

generates the following URL: `/api/{area}/controllerName`. And this can also generate conflicting actions if there are controllers with the same name in different areas.

**Comment by chsakell** [comment]
@bpiec  can you upgrade and try one of the following versions?

- ASP.NET Core 2.2:   **2.2.1.7**
- ASP.NET Core 3. :    **3.0.1.6**

**Comment by bpiec** [comment]
Did you commit the code too?

**Comment by chsakell** [comment]
Just did.

**Comment by bpiec** [comment]
You're awesome! Working like a charm.

I have one question however. Now it groups operations by the controller name. But if you have controllers with the same name in different areas it joins them into the same group (this is called `tags` in OpenAPI). Is it possible to change that and group by area name (or even `Area.Controller`)? Where's the code doing this? I thought `ApiDescriptionActionData` is responsible for that but I cannot see any setter usage for `GroupName`…

**Comment by chsakell** [comment]
Great news @bpiec , I am closing this issue as resolved. 

Your suggestion is very interesting, I am going to investigate it in the near future.

**Comment by bpiec** [comment]
For any future readers – this is how one can easily group operations using areas names:

```csharp
services.AddSwaggerGen(options =>
{
	// …

	options.TagActionsBy(selector =>
	{
		selector.ActionDescriptor.RouteValues.TryGetValue("area", out var area);
		var controller = selector.ActionDescriptor.RouteValues["controller"];
		return new[] {area != null ? $"{area}.{controller}" : controller};
	});

	// …
});
```
