### ISSUE TITLE
It did work when the template contains curly bracket

### ISSUE THREAD

**Issue by jack2gs** [chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting#2]
Hi,

Just found that, the api could not be discovered when the url template contains curly bracket. For example, /api/v3/order/{orderid}.

Could you take a look please?

the version is 3.0.1.7. The net core version is netcoreapp3.1.

Thanks,
Jack

**Comment by jack2gs** [comment]
Figured out. [FromRoute] needs for action parameters. cheers. :)

**Comment by DnlCYan** [comment]
@jack2gs what do you mean by 

> [FromRoute] needs for action parameters

?

I'm having the same problem. 
And I use MapControllerRoute like this:
`routes.MapControllerRoute(
	name: "UserInProjectGetUsersInProjectByFriendlyIds",
	pattern: "api/v1/usersInProject/{FriendlyIds}",
	defaults: new { action = "GetUsersInProjectByFriendlyIds", controller = "UserInProject" },
	constraints: new { httpMethod = new HttpMethodRouteConstraint(HttpMethod.Get.Method) }	
);`

I have to note that I have another one without {FriendlyIds} urlPath parameter that swagger generate. 
`routes.MapControllerRoute(
	name: "UserInProjectGetUsersInProject",
	pattern: "api/v1/usersInProject",
	defaults: new { action = "GetUsersInProject", controller = "UserInProject" },
	constraints: new { httpMethod = new HttpMethodRouteConstraint(HttpMethod.Get.Method) }
);`

Though there's no way to set the {FriendlyIds} urlPath parameter at swagger ui.

I tried {friendlyIds:required} with no luck, and if I use {friendlyIds?}, they both get's conflicted.

Can you help?
Thanks
Daniel Yan

**Comment by RufusJWB** [comment]
Thank you - I had the same problem!
