### ISSUE TITLE
Support for .NET Standard 2.0 and .NET Framework

### ISSUE THREAD

**Issue by bpiec** [chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting#3]
Since .NET Framework cannot use .NET Standard 2.1 based libraries, could you please add support for .NET Standard 2.0?

**Comment by chsakell** [comment]
For .NET Framework you can try [Swashbuckle.WebApi](https://github.com/domaindrivendev/Swashbuckle.WebApi).
.NET Standard 2.0 will not be supported on this package.

CS
