### ISSUE TITLE
set [ApiExplorerSettings(IgnoreApi = true)] to Controller not work

### ISSUE THREAD

**Issue by li-zhixin** [chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting#6]
Is there anything I can provide?

**Comment by chsakell** [comment]
`ApiExplorerSettings` is not meant actually to be used in conventional based routing. 
As of `4.0.1` version a new `SwaggerConfig` attribute added to support the `IgnoreApi` functionality
```csharp
[HttpGet]
[SwaggerConfig(IgnoreApi = true)]
public IActionResult Index([FromRoute] string message)
{
    return Ok(message ?? "Hello World!");
}
```
